export { default as Landing } from "./Landing"
export { default as Home } from "./Home"
export { default as Search } from "./Search"
export { default as Products } from "./Products"
export { default as Trending } from "./Trending"